// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PizzaData.Data;

#nullable disable

namespace PizzaData.Migrations
{
    [DbContext(typeof(PizzaDataContext))]
    partial class PizzaDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PizzaData.Models.Pizza", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmbientFermentationTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("FlourAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FlourName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FridgeFermentationTime")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("OliveOilAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("SaltAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("WaterAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("YeastAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Pizza");
                });
#pragma warning restore 612, 618
        }
    }
}
